"""Pure-Python OpenAPI server integration for zserio services.

This module provides :class:`OAServer`, a Connexion application subclass that
loads or generates an OpenAPI document for a zserio service, wires that document
to a user-provided controller module, and forwards incoming HTTP requests
through the zserio-generated Python service codec.

Use this module when Python is the server side of a zswag deployment. Client
side Python code normally uses the native :class:`zswag.OAClient` binding
instead.
"""

import connexion
import os
import inspect
import zserio
import sys
import yaml
from typing import Type
from flask import request as flask_request

from .pyzswagcl import \
    parse_openapi_config, \
    OAMethod

from .reflect import request_object_blob, service_method_request_type, to_snake

# Name of variable that is added to controller
# to hold the service instance.
CONTROLLER_SERVICE_INSTANCE = "_service"

# Name of OpenApi extension field from which connexion
# reads the target wsgi function.
CONTROLLER_OPENAPI_FIELD = "x-openapi-router-controller"

# Utility function for slash conversion in format strings
def to_slashes(s: str):
    """Return *s* with Windows path separators converted to forward slashes.

    The OpenAPI generator prints shell snippets and YAML paths. Forward slashes
    keep those snippets stable across platforms and avoid accidental escaping in
    generated command examples.
    """
    return s.replace("\\", "/")


# Raised if the controller passed to OAServer is missing a function
class IncompleteSchemaError(RuntimeError):
    """Raised when an OpenAPI document lacks a zserio service operation.

    ``OAServer`` verifies that every method generated for the zserio service is
    represented in the parsed OpenAPI config. This exception identifies the YAML
    file and service function name that caused the mismatch.
    """

    def __init__(self, schema_path: str, fn_name: str):
        super(IncompleteSchemaError, self).__init__(f"Missing operation `{fn_name}` in {schema_path}!")
        self.schema_path = schema_path
        self.fn_name = fn_name


class OAServer(connexion.App):
    """Connexion application that exposes a zserio service through OpenAPI.

    ``OAServer`` bridges three pieces that normally live separately:

    * a user controller module containing Python functions,
    * a zserio-generated ``ServiceInterface`` implementation, and
    * an OpenAPI YAML document generated by ``zswag.gen``.

    For every method in the zserio service, the server finds the corresponding
    snake_case function in the controller module, injects a service instance
    into that module, and installs a Connexion route handler that decodes HTTP
    parameters into a zserio request object before calling the controller.

    Parameters are keyword-only:

    ``controller_module``
        Python module that contains one function per service method. Method
        names are converted from zserio camelCase to Python snake_case.
    ``service_type``
        zserio-generated service class deriving from
        ``zserio.ServiceInterface``.
    ``zs_pkg_path``
        Optional zserio source package root used for documentation extraction
        when generating OpenAPI text.
    ``yaml_path``
        Optional OpenAPI YAML path. If omitted, the default path is derived from
        the generated service module. The file must already exist; if it does
        not, ``OAServer`` prints the matching ``python -m zswag.gen`` command
        and exits.

    If ``connexion[swagger-ui]`` is installed, Connexion exposes the interactive
    API UI at the configured ``/ui`` endpoint.
    """

    def __init__(self, *,
                 controller_module,
                 service_type: Type[zserio.ServiceInterface],
                 zs_pkg_path: str = None,
                 yaml_path: str = None):
        if not yaml_path:
            service_module = sys.modules[service_type.__module__]
            yaml_path = os.path.join(
                os.path.dirname(os.path.abspath(service_module.__file__)),
                f"{service_module.__name__.split('.')[-1]}.{service_type.__name__}.yaml")
            print(f"Using yaml path {yaml_path}")
        self.yaml_path = yaml_path
        yaml_parent_path = os.path.dirname(yaml_path)
        self.zs_pkg_path = zs_pkg_path

        # Initialise zserio service
        self.service_type = service_type
        assert inspect.isclass(self.service_type)

        # Initialise zserio service working instance
        self.controller_path = controller_module.__name__
        self.controller = controller_module
        self.service_instance_path = self.controller_path+f".{CONTROLLER_SERVICE_INSTANCE}"
        if not hasattr(self.controller, CONTROLLER_SERVICE_INSTANCE):
            setattr(self.controller, CONTROLLER_SERVICE_INSTANCE, self.service_type())
        self.service_instance = getattr(self.controller, CONTROLLER_SERVICE_INSTANCE)

        # Verify or generate yaml file
        if not os.path.isfile(yaml_path):
            print("\n" + inspect.cleandoc(f"""
                ERROR: File does not exist: {yaml_path}
                ----------------------------{"-"*len(yaml_path)}
                
                You can generate the file by running ...
                    
                    python -m zswag.gen \\
                        --service {self.service_instance.SERVICE_FULL_NAME} \\
                        --input "{
                            to_slashes(os.path.abspath(os.path.dirname(os.path.dirname(
                                __import__(self.service_type.__module__.split('.')[0]).__file__
                            ))))
                        }" \\
                        --config post,body \\
                        --output "{to_slashes(yaml_path)}"
                        
                    The --config argument is a comma-separated list of tags
                    to specify OpenAPI options. For more info, please run
                    
                        python -m zswag.gen --help
            """))
            exit(1)

        self.spec = parse_openapi_config(yaml_path)
        self.verify_openapi_schema()

        # Re-route service impl methods
        for method_name in self.service_instance.method_names:
            method_snake_name = to_snake(method_name)
            user_function = getattr(self.controller, method_snake_name)
            zserio_modem_function = getattr(self.service_instance, f"_{method_snake_name}_method")
            request_type = service_method_request_type(self.service_instance, method_name)
            assert zserio_modem_function

            if not user_function or not inspect.isfunction(user_function):
                print(f"WARNING: The controller {self.controller_path} does not implement {method_snake_name}!")
                continue

            print(f"Found {self.controller_path}.{method_snake_name}.")
            if len(inspect.signature(user_function).parameters) != 1:
                print(f"ERROR: {self.controller_path}.{method_snake_name} must have single 'request' parameter!")
                continue

            method_spec: OAMethod = self.spec[method_name]

            def wsgi_method(fun=zserio_modem_function, spec=method_spec, req_t=request_type, **kwargs):
                if spec.body_request_object:
                    request_blob = kwargs["body"]
                else:
                    request_blob = request_object_blob(
                        req_t=req_t,
                        spec=spec,
                        headers=flask_request.headers,
                        **kwargs)
                try:
                    return bytes(fun(request_blob, None).byte_array)
                except zserio.PythonRuntimeException as e:
                    if str(e).startswith("BitStreamReader"):
                        return "Error in BitStreamReader: Could not parse malformed request.", 400
                    else:
                        return f"Internal Server Error: {e}", 500
            setattr(self.service_instance, method_name, wsgi_method)

            def method_impl(request, ctx=None, fun=user_function):
                return fun(request)
            setattr(self.service_instance, f"_{method_snake_name}_impl", method_impl)

        # Load spec and inject openapi-router-controller
        print(f"Loading spec from {yaml_path} ...")
        with open(yaml_path, 'r') as swagger_file:
            openapi = yaml.load(swagger_file, Loader=yaml.FullLoader)
        for path_name, path_spec in openapi["paths"].items():
            for meth_name, method_spec in path_spec.items():
                if CONTROLLER_OPENAPI_FIELD not in method_spec:
                    method_spec[CONTROLLER_OPENAPI_FIELD] = self.service_instance_path
                else:
                    print(f"{meth_name} {path_name}: Using pre-set {CONTROLLER_OPENAPI_FIELD}.")

        # Initialise connexion app
        super(OAServer, self).__init__(
            self.controller_path,
            specification_dir=yaml_parent_path)

        # Add the API according to the verified yaml spec.
        self.add_api(
            openapi,
            arguments={"title": f"REST API for {service_type.__name__}"},
            pythonic_params=False)

    def verify_openapi_schema(self):
        """Verify that the parsed OpenAPI config covers every service method.

        The native parser returns a method map keyed by zserio operation name.
        This method compares that map against the generated service's
        ``method_names`` and raises :class:`IncompleteSchemaError` for the first
        missing operation.
        """
        for method_name in self.service_instance.method_names:
            if method_name not in self.spec:
                raise IncompleteSchemaError(self.yaml_path, method_name)
