from enum import Enum
import calculator.api as api
from zswag import Client


def run(host, port):

    # Calculator client generated by Zserio
    client = api.Calculator.Client(Client(f"http://{host}:{port}/openapi.json"))

    request = api.BaseAndExponent(api.I32(5), api.I32(2))
    print(client.powerMethod(request))
